/* Generated by scripts/bundle-content.mjs. Do not edit. */
(function (root) {
  "use strict";
// Shop URLs and shop-page listing capture for the worker command channel.
// Shop View itself is a local grid. This module only recognizes an Etsy shop
// page and reads the listing cards already on it.
const detectSearchBlock = globalThis.IscaleEtsy.detectSearchBlock;
const parseSearchResults = globalThis.IscaleEtsy.parseSearchResults;
const SHOP_NAME_RE = /^[A-Za-z0-9][A-Za-z0-9_-]{0,40}$/;

function buildShopUrl(shop, page = 1) {
  const name = String(shop || "").trim();
  if (!SHOP_NAME_RE.test(name)) return null;
  const url = new URL(`https://www.etsy.com/shop/${name}`);
  const n = Math.max(1, Number.parseInt(page, 10) || 1);
  if (n > 1) url.searchParams.set("page", String(n));
  return url.toString();
}

function parseShopTarget(value) {
  const raw = String(value || "").trim();
  if (!raw) return null;
  if (/^https?:\/\//i.test(raw)) {
    let parsed;
    try {
      parsed = new URL(raw);
    } catch {
      return null;
    }
    if (parsed.protocol !== "https:" || !/(^|\.)etsy\.com$/i.test(parsed.hostname)) return null;
    const match = parsed.pathname.match(/^\/shop\/([A-Za-z0-9][A-Za-z0-9_-]{0,40})(?:\/|$)/);
    if (!match) return null;
    const page = Math.max(1, Number.parseInt(parsed.searchParams.get("page") || "1", 10) || 1);
    return { shop: match[1], page, url: buildShopUrl(match[1], page) };
  }
  if (!SHOP_NAME_RE.test(raw)) return null;
  return { shop: raw, page: 1, url: buildShopUrl(raw, 1) };
}

function parseShopPage(doc, href, nowIso) {
  const target = parseShopTarget(href);
  const parsed = parseSearchResults(doc, href, nowIso);
  const page = target?.page || parsed.page || 1;
  const shop = target?.shop || "";
  return {
    shop,
    page,
    block: detectSearchBlock(doc),
    payload: {
      ...parsed,
      keyword: shop,
      page,
      results: (parsed.results || []).map((row, index) => ({
        ...row,
        page,
        position: index + 1,
        shopName: row.shopName || shop,
      })),
    },
  };
}
  var api = root.IscaleEtsy || (root.IscaleEtsy = {});
  api.buildShopUrl = buildShopUrl;
  api.parseShopTarget = parseShopTarget;
  api.parseShopPage = parseShopPage;
})(typeof globalThis !== "undefined" ? globalThis : this);
